name: Promote to Stable

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  promote:
    name: Promote canary to stable
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-tag canary as stable
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:canary
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:canary \
                     ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable
